name: "buildx-test-pubtodockerhub"

env:
  DOCKERHUB_IMAGE_PREFIX: abesesr/abes-hello

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  build-pubtodockerhub:
    permissions:
      id-token: write
      attestations: write
      contents: read
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout source code"
        uses: actions/checkout@v6
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Prepare version from git tags/branchs"
        id: docker_tag_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_IMAGE_PREFIX }}
          flavor: |
            latest=auto
            suffix=-front
      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Buildx and push"
        id: push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request'  && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/')) }}
          target: front-image
          tags: ${{ steps.docker_tag_meta.outputs.tags }}
